### ISSUE TITLE
Building is broken, and where can this be hosted?

### ISSUE THREAD

**Issue by eris-webserv** [cfoust/sour#4]
First off, love the project. Definitely would be cool! However, we people are poor and need to host this for free. Also, building is [BARK]ed. Where can we host and play this, and when will building be fixed??

**Comment by cfoust** [comment]
Hello! Indeed, building is broken right now. In general I'd like to come back and update this soon with a fix and further instructions, since even if you could build it's not obvious how one actually hosts this. I'm a bit busy this week, but may have more time within the coming weeks to really make this better.

As far as hosting costs go, the plan is for Sour to allow for players to create custom matches (even persistent servers) so since I host a version of it, that should negate the hosting costs for most users.

**Comment by eris-webserv** [comment]
Ah! Alright,

**Comment by Unkn0wnCreator** [comment]
I don't want to annoy you, but it would be great if you could somehow fix the problem so that I can run the application on my server. I'm really excited to be able to play the game in the web browser with my friends. But no matter what I do, earthly doesn't want me to build it even if I change the Ubuntu version  :(

**Comment by cfoust** [comment]
Argh, sorry about this, I will get to it as soon as I can!

**Comment by cfoust** [comment]
This is fixed now. `earthly +image` produces a correct, working image.
