### ISSUE TITLE
Nginx error

### ISSUE THREAD

**Issue by ETechTechnologies** [cfoust/sour#5]
============================ ❌ FAILURE [2. Build 🔧] ============================

Repeating the output of the command that caused the failure
         +image-slim *failed* | --> RUN apt-get update && apt-get install -y nginx
         +image-slim *failed* | Ign:1 http://archive.ubuntu.com/ubuntu groovy InRelease
         +image-slim *failed* | Ign:2 http://security.ubuntu.com/ubuntu groovy-security InRelease
         +image-slim *failed* | Ign:3 http://archive.ubuntu.com/ubuntu groovy-updates InRelease
         +image-slim *failed* | Err:4 http://security.ubuntu.com/ubuntu groovy-security Release
         +image-slim *failed* |   404  Not Found [IP: 91.189.88.142 80]
         +image-slim *failed* | Ign:5 http://archive.ubuntu.com/ubuntu groovy-backports InRelease
         +image-slim *failed* | Err:6 http://archive.ubuntu.com/ubuntu groovy Release
         +image-slim *failed* |   404  Not Found [IP: 91.189.88.142 80]
         +image-slim *failed* | Err:7 http://archive.ubuntu.com/ubuntu groovy-updates Release
         +image-slim *failed* |   404  Not Found [IP: 91.189.88.142 80]
         +image-slim *failed* | Err:8 http://archive.ubuntu.com/ubuntu groovy-backports Release
         +image-slim *failed* |   404  Not Found [IP: 91.189.88.142 80]
         +image-slim *failed* | Reading package lists...
         +image-slim *failed* | E: The repository 'http://security.ubuntu.com/ubuntu groovy-security Release' does not have a Release file.
         +image-slim *failed* | E: The repository 'http://archive.ubuntu.com/ubuntu groovy Release' does not have a Release file.
         +image-slim *failed* | E: The repository 'http://archive.ubuntu.com/ubuntu groovy-updates Release' does not have a Release file.
         +image-slim *failed* | E: The repository 'http://archive.ubuntu.com/ubuntu groovy-backports Release' does not have a Release file.
         +image-slim *failed* | Command /bin/sh -c 'apt-get update && apt-get install -y nginx' failed with exit code 100
         +image-slim *failed* |          +image-slim *failed* | ERROR: Command exited with non-zero code: RUN apt-get update && apt-get install -y nginx
Error: build target: build main: bkClient.Build: failed to solve: process "/bin/sh -c PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c 'apt-get update && apt-get install -y nginx'" did not complete successfully: exit code: 100

**Comment by LavaJockey** [comment]
This is due to Ubuntu Groovy not having nginx in its package list. Ubuntu Focal and such has nginx in it's package list and it will successfully install the package. I made a fork changing the version number from 20.10 to 20.04 and it passed the error, but overall the repository still won't work for me.

**Comment by cfoust** [comment]
Weird. I'm not sure what's going on here. I can take a look this weekend maybe.

**Comment by ETechTechnologies** [comment]
Thank you so much!

**Comment by cfoust** [comment]
Is this still happening on the `main` branch? For this reason I changed from `20.10` to `20.04` about a month ago.

**Comment by LavaJockey** [comment]
It looks like you fixed the version on CPP and not image-slim in the earthfile.

**Comment by ETechTechnologies** [comment]
> Is this still happening on the `main` branch? For this reason I changed from `20.10` to `20.04` about a month ago.

Yes, it is.

**Comment by cfoust** [comment]
Hey folks! I have great news. I did the following:
* Added support for GitHub Actions and now push a Docker image anyone can pull.
* Fixed the build so that anyone can build it. (This one was a little nasty. The problem is that the original BananaBread `Makefile` is really pretty hacky, it does a lot of copying of `.gitignore`ed files that have to be in the right place.)

You can now run Sour on a container orchestrator of your choosing:
```
docker run --rm -it -p 1234:1234 -p 28785:28785 ghcr.io/cfoust/sour
```
In my case, then I could play Sour on `http://localhost:1234/`.

Let me know if you still have any trouble.
